schema_sql = """-- SCHEMA for Outpass Management System
-- Run this in Supabase SQL editor (SQL -> New query)

-- USERS
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT CHECK (role IN ('student', 'warden', 'admin')) DEFAULT 'student',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- OUTPASSES
CREATE TABLE IF NOT EXISTS outpasses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  from_time TIME NOT NULL,
  to_time TIME NOT NULL,
  status TEXT CHECK (status IN ('Pending', 'Approved', 'Rejected')) DEFAULT 'Pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ATTENDANCE
CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  status TEXT CHECK (status IN ('Present', 'Absent')) NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- GATE LOGS
CREATE TABLE IF NOT EXISTS gate_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  action TEXT CHECK (action IN ('entry', 'exit')) NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- VIOLATIONS
CREATE TABLE IF NOT EXISTS violations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  reported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

def main():
    with open("schema.sql", "w", encoding="utf-8") as f:
        f.write(schema_sql)
    print("Wrote schema.sql to project root.")
    print()
    print("Please open Supabase → SQL editor → New query, paste the contents of schema.sql and run it.")
    print("This will create the necessary tables in your Supabase database.")
    print()
    print("File 'schema.sql' contains the SQL. After running, confirm in Supabase Table editor.")

if __name__ == "__main__":
    main()
